routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.index');
});

Route::get('/bangla_olympiad_2021', 'MainController@student_validation');
Route::get('/bangla_olympiad_2021/live_room', 'MainController@liveRoom');
Route::post('/bangla_olympiad_2021/live_new_room', 'MainController@liveNewRoom');

Route::post('/uploadTask', 'MainController@arts_upload');

Auth::routes();



Route::get('/school-dashboard', 'HomeController@index')->name('home');
Route::get('/school-profile', 'HomeController@profile');
Route::get('/school-profile/edit', 'HomeController@profileEdit');
Route::patch('/school-profile/update/{id}', 'HomeController@profileUpdate');

Route::get('/change-password', 'HomeController@setup');
Route::patch('/change-password/{id}', 'HomeController@changePassword');

Route::get('/getgroups', 'StudentController@getgroups');
Route::get('/getclass', 'StudentController@getclass');
Route::resource('/students', 'StudentController');

// =================Teaccher Routes=================

Route::get('/teachers/login', 'Teacher\Auth\TeacherLoginController@showTeacherLogin')->name('teacher.login');
Route::post('/teachers/login', 'Teacher\Auth\TeacherLoginController@Login');

Route::get('/teachers/dashboard', 'Teacher\Auth\TeacherController@index');

// ==============Admin Routes =================

Route::get('/admin', 'Admin\Auth\AdminLoginController@showAdminLogin')->name('admin.login');
Route::post('/admin', 'Admin\Auth\AdminLoginController@Login');


Route::get('admin/examiner_list', 'Admin\Teacher\TeacherController@teacherList');
Route::get('admin/add_examiner', 'Admin\Teacher\TeacherController@addTeacher');
Route::post('admin/addteacher', 'Admin\Teacher\TeacherController@createTeacher');
Route::get('admin/teacher/{id}/edit', 'Admin\Teacher\TeacherController@editTeacher');
Route::patch('admin/teacher/{id}', 'Admin\Teacher\TeacherController@updateTeacher');

Route::get('admin/teacher/profile/{id}', 'Admin\Teacher\TeacherController@viewProfile');
Route::get('admin/teacher/profile/edit/{id}', 'Admin\Teacher\TeacherController@editProfile');
Route::patch('admin/teacher/profile/update/{id}', 'Admin\Teacher\TeacherController@updateProfile');


Route::get('/admin/home', 'Admin\Auth\AdminController@index');
Route::get('/admin/user_list', 'Admin\Auth\AdminController@userList');
Route::get('/admin/register', 'Admin\Auth\AdminController@register');
Route::post('/admin/register', 'Admin\Auth\AdminController@registerUser');
Route::get('/admin/user/{id}/edit', 'Admin\Auth\AdminController@editUser');
Route::patch('/admin/user/{id}', 'Admin\Auth\AdminController@updateUser');
Route::get('/admin/user/changepassword', 'Admin\Auth\AdminController@changeUserPassword');
Route::patch('/admin/changepassword/{id}', 'Admin\Auth\AdminController@updatePassword');

Route::get('/admin/school_list', 'Admin\School\SchoolController@schoolList');
Route::get('/admin/school/{id}/edit', 'Admin\School\SchoolController@schoolEdit');
Route::patch('/admin/school/{id}', 'Admin\School\SchoolController@schoolUpdate');

Route::get('/admin/school/profile/{id}', 'Admin\School\SchoolController@schoolProfile');

Route::get('/admin/student_list', 'Admin\StudentController@studentList');

Route::resource('/admin/category', 'Admin\\CategoryController');
Route::resource('/admin/groups', 'Admin\\GroupController');



Route::get('/{any}', function ($any) {

  return Redirect::to('/');

})->where('any', '.*');

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable = [
    	'studentID',
        'name',
        'class',
        'email',
        'mobile',
        'reward',
        'status',
        'category_id',
        'group_id',
        'user_id',
        'code',
    ];



    public function user()
    {
        return $this->belongsTo('App\User');
    }
    public function category()
    {
        return $this->belongsTo('App\Category');
    }
    public function group()
    {
        return $this->belongsTo('App\Group');
    }
}

app/Http/Controllers/Admin/StudentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\User;
use App\Student;

class StudentController extends Controller
{

	public function __construct()
	{
	    $this->middleware('auth:admin');
	}

	
    public function studentList()
    {
    	$students = Student::all();
    	return view('admin.pages.students.index', compact('students'));
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\User;
use App\Category;
use App\Group;
use App\Student;

use Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\ServiceProvider;
use File;
use Image;
use Session;
use Redirect,Response;

class StudentController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = Student::where('user_id', '=', Auth::user()->id)->where('status', '=', '1')->orderBy('created_at', 'desc')->get();
        return view('students.index', compact('students'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $schools = User::where('status', '=', '1')->get();
        $category = Category::where('status', '=', '1')->get();
        return view('students.create', compact('schools', 'category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request);
        $request->validate([
                   'category_id' => 'required',
                   'group_id' => 'required',
                   'name' => 'required',
               ]);

        $val_data = Student::where('category_id', $request->category_id)->where('group_id', $request->group_id)->where('user_id', Auth::user()->id)->get();

        if(count($val_data)>2){
            return Redirect::to("/students")->withSuccess('Students add limited 3!');
        }else{
            $student = new Student();

            $student->studentID = time().rand(1111111,9999999);
            $student->name = $request->name;
            $student->class = $request->class;
            $student->email = $request->email;
            $student->mobile = $request->mobile;
            $student->category_id = $request->category_id;
            $student->group_id = $request->group_id;
            $student->user_id = Auth::user()->id;
            $student->code = rand(111,999)."IH".rand(111,999)."21";

            $student->save();

            return Redirect::to("/students")->withSuccess('Great! Students add successfully.');
        }
              
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $student = Student::FindOrFail($id);
        $schools = User::where('status', '=', '1')->get();
        $category = Category::where('status', '=', '1')->get();
        return view('students.edit', compact('schools', 'category', 'student'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
                   'category_id' => 'required',
                   'group_id' => 'required',
                   'name' => 'required',
               ]);

        $val_data = Student::where('category_id', $request->category_id)->where('group_id', $request->group_id)->where('user_id', Auth::user()->id)->get();

        if(count($val_data)>3){
            return Redirect::to("/students")->withSuccess('Students add limited 3!');
        }else{
            $student = Student::FindOrFail($id);

            $student->name = $request->name;
            $student->class = $request->class;
            $student->email = $request->email;
            $student->mobile = $request->mobile;
            $student->category_id = $request->category_id;
            $student->group_id = $request->group_id;
            $student->user_id = Auth::user()->id;

            $student->update();

            return Redirect::to("/students")->withSuccess('Great! Students info update successfully.');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


    public function getgroups(Request $request)
      {
          $data = Group::select('id', 'title', 'class_name')->where('category_id', $request->id)->where('status', '=', '1')->get();
         return response()->json($data); 
      }

      public function getclass(Request $request)
      {
         $data = Group::select('class_name')->where('id', $request->id)->get();
         return response()->json($data); 
      }
}

resources/views/students/create.blade.php
@extends('layouts.main')
@section('title', 'School Deshboard')
@section('content')
<div class="bg-light">
  <div class="container mt-4">
    <div class="row">
      <div class="col">
        <h3 class="mt-5"></h3>
      </div>
      
    </div>
  </div>
</div>
<div class="d-flex" id="wrapper">
  <!-- Sidebar -->
  <div class="bg-new-light border-right" id="sidebar-wrapper">
    <div class="sidebar-heading"> <b>School Deshboard</b>   </div>
    <hr>
    <div class="list-group list-group-flush">
      <a href="{{ url('/school-dashboard') }}" class="list-group-item list-group-item-action bg-new-light">Dashboard</a>
      <a href="{{ url('/school-profile') }}" class="list-group-item list-group-item-action bg-new-light">Profile</a>
      <a href="{{ route('students.index') }}" class="list-group-item list-group-item-action bg-new-light">Student List</a>
      <a href="{{ route('students.create') }}" class="list-group-item list-group-item-action bg-new-light">Add Student</a>
      <a href="#" class="list-group-item list-group-item-action bg-new-light">Submitted Task </a>
      <a href="{{ url('/change-password') }}" class="list-group-item list-group-item-action bg-new-light">Change Password</a>
    </div>
  </div>
  <div id="page-content-wrapper">
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
      <button class="btn btn-primary" id="menu-toggle"><i class="fa fa-bars" aria-hidden="true"></i></button>
      <h3 class="pl-3">Welcome to Bangla Olympiad 2021</h3>
    </nav>
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <h3 class="my-3">New Student Info Add</h3>
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <form method="post" action="{{ route('students.store') }}" enctype="multipart/form-data">
        {{ csrf_field() }}
        <div class="row">
          <div class="col-12 col-sm-6">
            <div class="form-group">
              <label for="exampleFormControlSelect1">Select Category</label>
              <select class="form-control demo2" name="category_id">
                <option value="" selected>Select A option</option>
                @foreach($category as $cat)
                <option value="{{ $cat->id }}">{{ $cat->title }}</option>
                @endforeach
                
              </select>
            </div>
            <div class="form-group">
              <label for="event_title">Group Name</label>
              <select class="form-control demo3 demo4 " name="group_id" required="required">
              </select>
            </div>
            <div class="form-group">
              <label for="event_title">Class</label>
              <select class="form-control demo5 " name="class">
              </select>
            </div>
            <div class="form-group">
              <label for="name">Student Name</label>
              <input type="text" name="name" class="form-control" id="name" placeholder="Name" required>
            </div>
            <div class="form-group">
              <label for="email">Student Email</label>
              <input type="email" name="email" class="form-control" id="email" placeholder="Email Address" required>
            </div>
            <div class="form-group">
              <label for="email">Student Mobile</label>
              <input type="text" name="mobile" class="form-control" id="email" placeholder="Mobile Number" required>
            </div>
            <button type="submit" class="btn btn-success">Save Participant</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
@endsection



@section('java_script')
<script>
$(document).ready(function(){
$(document).on('change', '.demo2', function(){
// console.log('It is ok');
var category_id = $(this).val();
var opp= " ";
$.ajax({
type:'get',
url:'{{ url('/getgroups')}}',
data:{ 'id' : category_id},
success: function(data){
opp+= '<option value="0" selected disabled >--select an option-- </option>';
for (var i = 0; i < data.length; i++) {
opp+= '<option value="'+ data[i].id +'">'+ data[i].title + '</option>';
}
$('.demo3').html(opp);
},
error:function(){
}
});
});
});
$(document).ready(function(){
$(document).on('change', '.demo4', function(){
//
var group_id = $(this).val();
var oppn= " ";
$.ajax({
type:'get',
url:'{{ url('/getclass')}}',
data:{ 'id' : group_id},
// console.log('It is ok'),
success: function(data){
var opp = "";
for (var i = 0; i < data.length; i++) {
opp+=  data[i].class_name;
}
var array = opp.split(',');
oppn+= '<option value="0" selected disabled >--select an option-- </option>';
for (var i = 0; i < array.length; i++) {
oppn+= '<option value="'+ array[i] +'">'+ array[i]  + '</option>';
}
$('.demo5').html(oppn);
},
error:function(){
}
});
});
});
</script>
@endsection

resources/views/students/edit.blade.php
@extends('layouts.main')

@section('title', 'School Deshboard')

@section('content')

<div class="bg-light">
	<div class="container mt-4">
		<div class="row">
			<div class="col">
				<h3 class="mt-5"></h3>
			</div>
			
		</div>
	</div>
</div>



  <div class="d-flex" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-new-light border-right" id="sidebar-wrapper">
      <div class="sidebar-heading"> <b>School Deshboard</b>   </div>
      <hr>
      <div class="list-group list-group-flush">
        <a href="{{ url('/school-dashboard') }}" class="list-group-item list-group-item-action bg-new-light">Dashboard</a>
        <a href="{{ url('/school-profile') }}" class="list-group-item list-group-item-action bg-new-light">Profile</a>
        <a href="{{ route('students.index') }}" class="list-group-item list-group-item-action bg-new-light">Student List</a>
        <a href="{{ route('students.create') }}" class="list-group-item list-group-item-action bg-new-light">Add Student</a>
        <a href="#" class="list-group-item list-group-item-action bg-new-light">Submitted Task </a>
        <a href="{{ url('/change-password') }}" class="list-group-item list-group-item-action bg-new-light">Change Password</a>
      </div>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">

      <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <button class="btn btn-primary" id="menu-toggle"><i class="fa fa-bars" aria-hidden="true"></i></button> 
        <h3 class="pl-3">Welcome to Bangla Olympiad 2021</h3>
 
      </nav>

      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <h3 class="my-3">Student Info Edit</h3>
          </div>
        </div>
      </div>

      <div class="container-fluid">
        <div class="">
          <form method="post" action="{{ route('students.update', $student->id) }}" enctype="multipart/form-data">
            {{ method_field('PATCH') }}
            {{ csrf_field() }}
            <div class="row">
              <div class="col-12 col-sm-6">
                <div class="form-group">
                  <label for="exampleFormControlSelect1">Select Category</label>
                  <select class="form-control demo2" name="category_id">
                    <option value="{{ $student->category_id }}" selected>{{ $student->category->title }}</option>
                    @foreach($category as $cat)
                    <option value="{{ $cat->id }}">{{ $cat->title }}</option>
                    @endforeach
                    
                  </select>
                </div>
                <div class="form-group">
                  <label for="event_title">Group Name</label>
                  <select class="form-control demo3 demo4 " name="group_id" required="required">
                    <option value="{{ $student->group_id }}" selected>{{ $student->group->title }}</option>
                  </select>
                </div>
                <div class="form-group">
                  <label for="event_title">Class</label>
                  <select class="form-control demo5 " name="class">
                    <option value="{{ $student->class }}" selected>{{ $student->class }}</option>
                  </select>
                </div>
                <div class="form-group">
                  <label for="name">Student Name</label>
                  <input type="text" name="name" class="form-control" id="name" value="{{ $student->name }}" required>
                </div>
                <div class="form-group">
                  <label for="email">Student Email</label>
                  <input type="email" name="email" class="form-control" id="email" value="{{ $student->email }}" required>
                </div>
                <div class="form-group">
                  <label for="email">Student Mobile</label>
                  <input type="text" name="mobile" class="form-control" id="email" value="{{ $student->mobile }}" required>
                </div>
                <button type="submit" class="btn btn-success">Update Participant</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>

  </div>




@endsection



@section('java_script')
<script>
$(document).ready(function(){
$(document).on('change', '.demo2', function(){
// console.log('It is ok');
var category_id = $(this).val();
var opp= " ";
$.ajax({
type:'get',
url:'{{ url('/getgroups')}}',
data:{ 'id' : category_id},
success: function(data){
opp+= '<option value="0" selected disabled >--select an option-- </option>';
for (var i = 0; i < data.length; i++) {
opp+= '<option value="'+ data[i].id +'">'+ data[i].title + '</option>';
}
$('.demo3').html(opp);
},
error:function(){
}
});
});
});
$(document).ready(function(){
$(document).on('change', '.demo4', function(){
//
var group_id = $(this).val();
var oppn= " ";
$.ajax({
type:'get',
url:'{{ url('/getclass')}}',
data:{ 'id' : group_id},
// console.log('It is ok'),
success: function(data){
var opp = "";
for (var i = 0; i < data.length; i++) {
opp+=  data[i].class_name;
}
var array = opp.split(',');
oppn+= '<option value="0" selected disabled >--select an option-- </option>';
for (var i = 0; i < array.length; i++) {
oppn+= '<option value="'+ array[i] +'">'+ array[i]  + '</option>';
}
$('.demo5').html(oppn);
},
error:function(){
}
});
});
});
</script>
@endsection

resources/views/students/index.blade.php
@extends('layouts.main')

@section('title', 'School Deshboard')

@section('content')

<div class="bg-light">
	<div class="container mt-4">
		<div class="row">
			<div class="col">
				<h3 class="mt-5"></h3>
			</div>
			
		</div>
	</div>
</div>



  <div class="d-flex" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-new-light border-right" id="sidebar-wrapper">
      <div class="sidebar-heading"> <b>School Deshboard</b>   </div>
      <hr>
      <div class="list-group list-group-flush">
        <a href="{{ url('/school-dashboard') }}" class="list-group-item list-group-item-action bg-new-light">Dashboard</a>
        <a href="{{ url('/school-profile') }}" class="list-group-item list-group-item-action bg-new-light">Profile</a>
        <a href="{{ route('students.index') }}" class="list-group-item list-group-item-action bg-new-light">Student List</a>
        <a href="{{ route('students.create') }}" class="list-group-item list-group-item-action bg-new-light">Add Student</a>
        <a href="#" class="list-group-item list-group-item-action bg-new-light">Submitted Task </a>
        <a href="{{ url('/change-password') }}" class="list-group-item list-group-item-action bg-new-light">Change Password</a>
      </div>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">

      <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <button class="btn btn-primary" id="menu-toggle"><i class="fa fa-bars" aria-hidden="true"></i></button> 
        <h3 class="pl-3">Welcome to Bangla Olympiad 2021</h3>

      </nav>



      <div class="container-fluid">
        @if ($message = Session::get('success'))
        <hr>
           <div class="alert alert-success alert-block">
              <button type="button" class="close" data-dismiss="alert">×</button>
              <strong>{{ $message }}</strong>
           </div>
           <br>
        <hr>
        @endif
        <div class="row">
          <div class="col-12 p-3">
            <table class="table table-bordered">
              <thead>
                <th>Sl No.</th>
                <th>Student Code</th>
                <th>Student Name</th>
                <th>Student Mobile</th>
                <th>Category Title</th>
                <th>Group Name</th>
                <th>Action</th>
              </thead>
              <tbody>
                @foreach($students as $student)
                <tr>
                  <td>{{ $loop->iteration  }}</td>
                  <td>{{ $student->code }}</td>
                  <td>{{ $student->name }}</td>
                  <td>{{ $student->mobile }}</td>
                  <td>{{ $student->category->title }}</td>
                  <td>{{ $student->group->title }}</td>
                  <td>
                    <a class="btn btn-sm btn-info" href="{{ route('students.edit', $student->id) }}">Edit</a>
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

  </div>




@endsection